### ISSUE TITLE
Warn against the use of `textContent`

### ISSUE THREAD

**Issue by BrannenGH** [playwright-community/eslint-plugin-playwright#127]
Hi all,

We've run into some issues with playwright tests using `textContent` over `innerText` to validate text rendered in the browser. 

[Since `innerText` takes CSS styling into account and better reflects what is rendered on the page](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext), I'd like a rule that could warn developers when using `textContent`, and instead push folks to use `innerText`, unless they have a specific reason not to.

Thank you!

**Comment by mskelton** [comment]
Honestly both of these should be discouraged from use. In general, using web based assertions (`toHaveText`) is what you should be using.

**Comment by BrannenGH** [comment]
Thanks for the feedback Mark, that's a good point. We have a few places where we're referencing `textContent` outside of an assertion, but I think a majority of the places that have `textContent` should probably use `toHaveText` instead. 

Would an ideal lint rule check if the assertion is within an `expect` expression, then also suggest `toHaveText`, besides suggesting `innerText`?

**Comment by mskelton** [comment]
@BrannenGH I already have a work in progress PR that will warn about using `innerText` or `textContent` and instead suggest `toHaveText`, so that part is covered.

https://github.com/playwright-community/eslint-plugin-playwright/pull/129

Outside of expect calls, I don't really thing we should be warning, if you are using them outside of an expect call, it's probably valid.
