### ISSUE TITLE
Incorrect validTitle error flag

### ISSUE THREAD

**Issue by toduyemi** [playwright-community/eslint-plugin-playwright#312]
Example => 
<img width="744" alt="Screenshot 2024-08-22 at 10 52 32 AM" src="https://github.com/user-attachments/assets/8902be13-31a5-4490-8aa6-b90573d8557f">

Title is a string yet an error is thrown.

**Comment by mskelton** [comment]
The rule doesn't do semantic analysis, and doesn't have type information, so this is expected.

**Comment by toduyemi** [comment]
This doesn't make sense. The rule says title must be a string... the title is a string... and it's calling an error. That is by every definition a bug. What's the intention behind this rule?

If the rule only sees string-literals as valid, that's poor coding practices. Why is a linter advocating for it? Even still, if this is expected behaviour, it should say that in the rule/documentation. 

https://github.com/playwright-community/eslint-plugin-playwright/blob/main/docs/rules/valid-title.md => Nowhere does it indicate developers storing strings in variables for titles is invalid. This is an extremely common practice

`"Title must be a string literal."`

**Comment by mskelton** [comment]
@toduyemi It's not a bug, this plugin does not use type information and thus cannot in all circumstances determine the type of the variable. We could add some amount of logic to make that work in the current file, but it's such a rare thing its not worth the effort.

The rule was ported from the Jest ESLint plugin as part of our effort to provide compatibility and feature completeness between the two.  I do think it's a fine rule, test titles with a variable instead of a string literal is a super rare case, so I don't really care to handle most of the rare exceptions to this rule.
