### ISSUE TITLE
Error or warning on the `pause` calls

### ISSUE THREAD

**Issue by Nauss** [playwright-community/eslint-plugin-playwright#34]
I recently switched from Spectron to Playwright to test an Electron app and I'm loving the experience so far.

I'm (over?)using the mighty `await page.pause()` to develop and debug my tests. And of course, I sometimes forget to remove one of these which causes some troubles later.

It would be nice to have the linter optionally produce warnings (or errors)  for the `pause()` calls.

What do you think ?

**Comment by mskelton** [comment]
This feels like something that could be implemented in the core of Playwright test similar to `forbidOnly`.  @mxschmitt Thoughts on this one?

**Comment by mxschmitt** [comment]
When running the tests headless it should ignore page.pause() calls afaik, regarding adding it to the test-runner, I'd personally prefer it in the eslint plugin instead, because the test-runner is pretty framework/Playwright agnostic and we need to be careful with adding more pw related CLI/config flags there.
